### ISSUE TITLE
Laravel 11 Not Supported

### ISSUE THREAD

**Issue by ahmadnajmdev** [First-Iraqi-Bank/fib-laravel-payment-sdk#10]
Please upgrade this package to support laravel 11 projects

Error:
composer require First-Iraqi-Bank/fib-laravel-payment-sdk
./composer.json has been updated
Running composer update first-iraqi-bank/fib-laravel-payment-sdk
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - first-iraqi-bank/fib-laravel-payment-sdk[1.0.3, ..., 1.0.4] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - first-iraqi-bank/fib-laravel-payment-sdk[1.0.5, ..., 1.0.7] require illuminate/contracts ^8.0 || ^9.0 || ^10.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.22] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires first-iraqi-bank/fib-laravel-payment-sdk * -> satisfiable by first-iraqi-bank/fib-laravel-payment-sdk[1.0.3, ..., 1.0.7].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require First-Iraqi-Bank/fib-laravel-payment-sdk:*" to figure out if any version is installable, or "composer require First-Iraqi-Bank/fib-laravel-payment-sdk:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by omer-hanaraey** [comment]
@ahmadnajmdev thanks for addressing this issue, and it has been addressed in this PR [https://github.com/First-Iraqi-Bank/fib-laravel-payment-sdk/pull/12](url)
